name: identity

services:

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: identity-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - identity-network

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    container_name: identity-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped
    networks:
      - identity-network

  pubsub-emulator:
    image: google/cloud-sdk:${GCLOUD_VERSION}
    container_name: identity-pubsub-emulator
    ports:
      - "8085:8085"
    environment:
      - PUBSUB_PROJECT_ID=local-dev
    command: >
      gcloud beta emulators pubsub start 
      --project=local-dev
      --host-port=0.0.0.0:8085
    restart: unless-stopped
    networks:
      - identity-network

volumes:
  postgres-data:

networks:
  identity-network:
    